<?php

return [
    'name' => 'PT. Syirkah Mandiri Artomoro',
    'short_name' => 'SMA',
    'tagline' => 'Industrial Supply & Integrated Technical Solutions',
    'positioning' => 'General Supplier - Engineering - Mechanical - Electrical - Instrumentation',
    'description' => 'PT. Syirkah Mandiri Artomoro bergerak sebagai general supplier sekaligus penyedia solusi teknis untuk kebutuhan industrial equipment, spare parts, dan engineering solutions.',
    'logo' => '/images/logo-smart.png',
    'hero' => '/images/industrial-hero.png',
    'contact' => [
        'address_lines' => [
            'Jalan Teladan No. 7, RT 04/RW 10',
            'Kel. Simpang Baru, Kec. Bina Widya',
            'Kota Pekanbaru, Provinsi Riau 28293',
        ],
        'phone' => '+62 812-6672-3815',
        'emails' => [
            'doni.rahmat@smartomoro.com',
            'admin@smartomoro.com',
        ],
    ],
    'legal' => [
        [
            'label' => 'NPWP',
            'value' => 'Menunggu konfirmasi owner',
            'note' => 'Struktur informasi legal sudah disiapkan sesuai PRD.',
        ],
        [
            'label' => 'SK Kemenkumham',
            'value' => 'Menunggu konfirmasi owner',
            'note' => 'Nomor dokumen legal perlu divalidasi sebelum dipublikasikan.',
        ],
        [
            'label' => 'NIB',
            'value' => 'Menunggu konfirmasi owner',
            'note' => 'Informasi NIB belum tersedia di PRD.',
        ],
    ],
    'focuses' => [
        [
            'title' => 'Engineering',
            'description' => 'Solusi teknis berbasis spesifikasi lapangan, kebutuhan proses, dan standar operasional industri.',
            'image' => '/images/expertise-engineering.png',
        ],
        [
            'title' => 'Mechanical',
            'description' => 'Pengadaan komponen mekanikal, rotating equipment, pompa, hose, compressor, dan spare parts.',
            'image' => '/images/expertise-mechanical.png',
        ],
        [
            'title' => 'Electrical',
            'description' => 'Motor listrik, generator, drive control, high-voltage motor, dan kebutuhan sistem kelistrikan.',
            'image' => '/images/expertise-electrical.png',
        ],
        [
            'title' => 'Instrumentation',
            'description' => 'Peralatan monitoring, metering, kontrol proses, dan instrumentasi untuk akurasi operasi.',
            'image' => '/images/expertise-instrumentation.png',
        ],
        [
            'title' => 'Oil Spill Response & Prevention',
            'description' => 'Produk pencegahan dan penanganan tumpahan minyak untuk area marine, port, dan oil & gas.',
            'image' => '/images/expertise-oil-spill.png',
        ],
    ],
    'values' => [
        ['title' => 'Supply / Procurement', 'description' => 'Equipment dan spare part industri dari principal atau OEM yang sesuai kebutuhan pelanggan.'],
        ['title' => 'Technical Solution', 'description' => 'Rekomendasi produk menyesuaikan spesifikasi teknis, proses, dan kebutuhan lapangan.'],
        ['title' => 'Reliability & Efficiency', 'description' => 'Diarahkan untuk meningkatkan operational continuity, safety, dan environmental protection.'],
        ['title' => 'Safety & Environmental Protection', 'description' => 'Mendukung operasi yang lebih aman dan kesiapan terhadap risiko lingkungan.'],
    ],
    'benefits' => [
        'Reliability',
        'Efficiency',
        'Operational Continuity',
        'Safety',
        'Environmental Protection',
    ],
    'products' => [
        [
            'slug' => 'electric-motors-generators',
            'category' => 'Electrical',
            'name' => 'Electric Motors & Generators',
            'brand' => 'Wolong',
            'summary' => 'Motor listrik, generator, PM motors, drive control, dan high-voltage motor.',
            'description' => 'Solusi motor dan generator untuk kebutuhan kelistrikan industri, utilitas, dan fasilitas produksi.',
            'applications' => ['Manufacturing', 'Oil & Gas', 'Mining', 'Infrastructure', 'Utility'],
            'specifications' => [
                'Product scope' => 'Electric motors, generators, PM motors, drive control',
                'Use case' => 'Power transmission, production equipment, industrial drive system',
                'Inquiry data' => 'Power rating, voltage, speed, mounting, enclosure, operating environment',
            ],
            'datasheet' => null,
        ],
        [
            'slug' => 'vibration-technology',
            'category' => 'Mechanical',
            'name' => 'Vibration Technology',
            'brand' => 'OLI',
            'summary' => 'Internal/external vibrator, screen vibrator, frequency & voltage converter.',
            'description' => 'Teknologi vibrasi untuk handling material, screening, batching, dan proses produksi.',
            'applications' => ['Mining', 'Construction', 'Cement', 'Manufacturing'],
            'specifications' => [
                'Product scope' => 'Internal vibrator, external vibrator, screen vibrator, converter',
                'Use case' => 'Material flow, compaction, screening, conveying support',
                'Inquiry data' => 'Material type, capacity, installation position, frequency, voltage',
            ],
            'datasheet' => null,
        ],
        [
            'slug' => 'chemical-metering-pump',
            'category' => 'Instrumentation',
            'name' => 'Chemical Metering Pump',
            'brand' => 'Qdos',
            'summary' => 'Chemical dosing pump untuk kebutuhan dosing bahan kimia.',
            'description' => 'Pompa metering untuk dosing bahan kimia yang membutuhkan akurasi dan konsistensi.',
            'applications' => ['Chemical', 'Water Treatment', 'Pharmaceutical', 'Manufacturing'],
            'specifications' => [
                'Product scope' => 'Chemical dosing pump',
                'Use case' => 'Chemical dosing, treatment process, controlled fluid transfer',
                'Inquiry data' => 'Chemical type, flow rate, pressure, concentration, duty cycle',
            ],
            'datasheet' => null,
        ],
        [
            'slug' => 'hose-pump',
            'category' => 'Mechanical',
            'name' => 'Hose Pump',
            'brand' => 'Bredel',
            'summary' => 'Hose pump untuk slurry, bahan kimia korosif, dan fluida kental.',
            'description' => 'Pompa hose untuk aplikasi fluida abrasif, korosif, viscous, dan proses berat.',
            'applications' => ['Mining', 'Chemical', 'Wastewater', 'Manufacturing'],
            'specifications' => [
                'Product scope' => 'Hose pump',
                'Use case' => 'Slurry handling, corrosive chemical transfer, viscous fluid transfer',
                'Inquiry data' => 'Fluid type, solids content, flow rate, pressure, temperature',
            ],
            'datasheet' => null,
        ],
        [
            'slug' => 'industrial-hose',
            'category' => 'Mechanical',
            'name' => 'Industrial Hose',
            'brand' => 'Aflex',
            'summary' => 'Corroline+ PTFE hose untuk aplikasi industri.',
            'description' => 'Industrial hose untuk aplikasi transfer fluida yang menuntut chemical resistance dan durability.',
            'applications' => ['Chemical', 'Pharmaceutical', 'Food Process', 'Manufacturing'],
            'specifications' => [
                'Product scope' => 'PTFE hose',
                'Use case' => 'Chemical transfer, clean process, high-resistance fluid line',
                'Inquiry data' => 'Fluid, pressure, temperature, connection, length, certification need',
            ],
            'datasheet' => null,
        ],
        [
            'slug' => 'air-compressor',
            'category' => 'Mechanical',
            'name' => 'Air Compressor',
            'brand' => 'Tecbell',
            'summary' => 'Air compressor dan refrigerated dryer untuk kebutuhan udara tekan.',
            'description' => 'Sistem udara tekan untuk fasilitas produksi, workshop, dan kebutuhan utilitas industri.',
            'applications' => ['Manufacturing', 'Workshop', 'Infrastructure', 'General Industry'],
            'specifications' => [
                'Product scope' => 'Air compressor, refrigerated dryer',
                'Use case' => 'Compressed air utility, pneumatic tools, plant operation',
                'Inquiry data' => 'Capacity, pressure, air quality, duty cycle, installation environment',
            ],
            'datasheet' => null,
        ],
        [
            'slug' => 'oil-spill-response-prevention',
            'category' => 'Oil Spill Response',
            'name' => 'Oil Spill Response & Prevention',
            'brand' => 'BLU-C',
            'summary' => 'Oil boom, absorbent, skimmer, dispersant, spray system, dan spill kit.',
            'description' => 'Peralatan pencegahan dan respons tumpahan minyak untuk marine, port, dan area operasi berisiko.',
            'applications' => ['Marine', 'Port', 'Oil & Gas', 'Environmental Response'],
            'specifications' => [
                'Product scope' => 'Oil boom, absorbent, skimmer, dispersant, spray system, spill kit',
                'Use case' => 'Oil spill prevention, emergency response, containment, recovery',
                'Inquiry data' => 'Area coverage, water condition, oil type, response scenario, storage needs',
            ],
            'datasheet' => null,
        ],
    ],
    'brands' => [
        ['slug' => 'oli', 'name' => 'OLI', 'focus' => 'Vibration Technology', 'description' => 'Principal untuk teknologi vibrasi industri seperti vibrator, screen vibrator, dan converter.'],
        ['slug' => 'wolong', 'name' => 'Wolong', 'focus' => 'Electric Motors & Generators', 'description' => 'Principal untuk motor listrik, generator, PM motors, drive control, dan high-voltage motor.'],
        ['slug' => 'qdos', 'name' => 'Qdos', 'focus' => 'Chemical Metering', 'description' => 'Brand untuk kebutuhan chemical metering dan dosing pump.'],
        ['slug' => 'bredel', 'name' => 'Bredel', 'focus' => 'Hose Pump', 'description' => 'Brand hose pump untuk fluida abrasif, korosif, kental, dan aplikasi berat.'],
        ['slug' => 'aflex', 'name' => 'Aflex', 'focus' => 'Industrial Hose', 'description' => 'Brand industrial PTFE hose untuk kebutuhan transfer fluida industri.'],
        ['slug' => 'tecbell', 'name' => 'Tecbell', 'focus' => 'Air Compressor', 'description' => 'Brand air compressor dan refrigerated dryer untuk kebutuhan udara tekan.'],
        ['slug' => 'blu-c', 'name' => 'BLU-C', 'focus' => 'Oil Spill Response & Prevention', 'description' => 'Brand solusi oil spill response, prevention, containment, dan recovery.'],
    ],
    'industries' => [
        ['name' => 'Pertambangan', 'description' => 'Conveyor, screening, vibration, slurry handling, dan operasi heavy-duty.'],
        ['name' => 'Oil & Gas', 'description' => 'Equipment proses, mechanical parts, marine response, dan oil spill prevention.'],
        ['name' => 'Kimia & Farmasi', 'description' => 'Dosing, transfer, hose, dan peralatan fluida khusus.'],
        ['name' => 'Manufacturing', 'description' => 'Motor, compressor, instrumentation, dan kebutuhan maintenance.'],
        ['name' => 'Marine & Port', 'description' => 'Oil spill kit, boom, absorbent, skimmer, dan response equipment.'],
        ['name' => 'Infrastruktur', 'description' => 'Supply equipment untuk proyek, utilitas, dan fasilitas kritikal.'],
    ],
];
